version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rong-datedrop
    env_file:
      - .env
    ports:
      - "3001:3000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: unless-stopped
